updating Makefile to use pkg-config for determining of CFLAGS and LIBS of OpenCV
It was causing error in case of compiling against OpenCV 3.0.0:

/usr/bin/ld: /tmp/cckWdv8g.o: undefined reference to symbol 'cvWriteFrame'
/lib/libopencv_videoio.so.3.0: error adding symbols: DSO missing from command line